services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: smart-bike-zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:latest
    container_name: smart-bike-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'

  # Kafka UI for development and monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: smart-bike-kafka-ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: smart-bike
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
